name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  main:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 16379:6379
        options: >-
          -v ${{ github.workspace }}/redis.sh:/usr/local/bin/redis.sh
          --entrypoint /usr/local/bin/redis.sh
    steps:
    # Downloads a copy of the code in your repository before running CI tests
    - name: Check out repository code
      uses: actions/checkout@v3

    # Performs a clean installation of all dependencies in the `package.json` file
    # For more information, see https://docs.npmjs.com/cli/ci.html
    - name: Install dependencies
      run: npm ci

    - name: Connect to Redis
      # Runs a script that creates a Redis client, populates
      # the client with data, and retrieves data
      run: node client.js
      # Environment variable used by the `client.js` script to create
      # a new Redis client.
      env:
        # The hostname used to communicate with the Redis service container
        REDIS_HOST: localhost
        # The default Redis port
        REDIS_PORT: 16379
        REDIS_PASSWORD: redis
